packages:
  - "apps/*"
  - "packages/*"
  - "packages/embedding/*"
  - "packages/llm/*"
  - "packages/core/tests"
  - "packages/llamaindex/tests"
  - "packages/llamaindex/e2e"
  - "packages/llamaindex/e2e/examples/*"
  - "packages/autotool/examples/*"
  - "examples/"
  - "examples/**"
