name: E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  e2e:
    name: E2E Tests on create-llama
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 20]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: ./packages/create-llama
      - name: Build create-llama
        run: pnpm run build
        working-directory: ./packages/create-llama
      - name: Run Playwright tests
        run: pnpm exec playwright test
        working-directory: ./packages/create-llama
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./packages/create-llama/playwright-report/
          retention-days: 30
